apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: no-app
  namespace: test-example2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: weave-gitops
    server: {{ .Values.spec.destination.server }}
  project: test
  source:
    path: kustomize-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
