apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: test-example1
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sample-example1
    server: {{ .Values.spec.destination.server }}
  project: sample
  source:
    path: kustomize-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
